version: '3.8'

services:
  wso2:
    image: wso2/wso2am:4.1.0
    container_name: api-manager
    ports:
    - "8280:8280"
    - "8243:8243" 
    - "9443:9443" # /carbon   /devportal   /publisher
    - "9999:9999"   #jmx
    - "11111:11111" #jmx
    volumes:
      - ./deployment.toml:/home/wso2carbon/repository/conf/deployment.toml:ro
      - ./logs:/home/wso2carbon/repository/logs/

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    # entrypoint: ["bash", "-c", "jmeter -n -t bin/examples/CSVSample.jmx -l bin/examples/mytest1.jtl"]
    entrypoint: ["bash", "-c", "jmeter"]
    volumes:
      - ./jmeter/results/:/opt/apache-jmeter-5.5/bin/examples/